[package]
name = "rust_chess"
version = "0.1.0"
authors = ["axelamit <axel.v.nilsson@gmail.com>",
            "Malte Blomqvist <maltebl@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
